### ISSUE TITLE
Issue with installing optimum

### ISSUE THREAD

**Issue by droy117** [Kevin-Duignan/MACathon-noname#2]
Hi, I really liked your project so I was trying to study it and decided to clone in my local system. But I can't find a way to install optimum. I always get this error after ` pip install -r requirements.txt `
```
Traceback (most recent call last):
        File "<string>", line 7, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'optimum/version.py'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/debak/Desktop/Youtube-Comment-Analyser/venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/debak/Desktop/Youtube-Comment-Analyser/venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/debak/Desktop/Youtube-Comment-Analyser/venv/lib64/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0fawd88j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0fawd88j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0fawd88j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-0fawd88j/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      AssertionError: Error: Could not open 'optimum/version.py' due [Errno 2] No such file or directory: 'optimum/version.py'
```

It would be great if you could help me fix this issue. 

Thank You.

**Comment by WIZN0DE** [comment]
Sorry, found the issue. It was a version error I was running Python 3.12, and after downgrading it to 3.7 it worked.
